name: Deploy CUDA

env:
  image_name: fyl080801/comfyui-cuda

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 从 GitHub 拉取代码
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Clone ComfyUI repository
        run: |
          git clone https://github.com/comfyanonymous/ComfyUI.git ComfyUI

      # 登录到 GitHub Container Registry (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Extract metadata for Docker
    #     id: meta
    #     uses: docker/metadata-action@v5
    #     with:
    #       images: ghcr.io/${{ env.image_name }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.image_name }}:1.0.0 .

      # 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker image
        run: docker push ghcr.io/${{ env.image_name }}:1.0.0
